# Generated by Django 4.2.9 on 2026-05-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='user',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CIN'),
        ),
    ]
